### PR TITLE
Log updated packages commits titles.

### PR DESCRIPTION
**Pull request by wviana**
Hello,
First of all thank you very much for this project, I've choose to use it cause I was beginning in Lua and thought paq so simple and interesting. After a long time using it I missed a feature. I would like to see what was updated when run PaqUpdate. So I tried to implement it myself.

So I've add one more parameter into call_proc that sets stderr as sub-process stdout. Made this so when I call the git command that list updates ( titles of commities since last update). ` call_proc("git", { "log", "--pretty=format:* %s", prev_hash .. ".." .. cur_hash }, pkg.dir, function(ok) end, true)`.
To not break anything I passed empty function.

I also created a log function for print package name follow by "updating..." before listing each package update.

Hope you like it.

### CODE REVIEW

**Comment by savq** [comment]
hi @wviana,

I guess it's reasonable to put the `git log` in the log file, hadn't thought of that 😄. It might be worthwhile to do a refactor so the file is opened just once, but for now it's good enough as it is. Thank you.

**Comment by wviana** [comment]
Just notice everything getting out of order. Maybe cause multiple open of same file as you said. Will try to fix it later.

**Comment by David-Else** [comment]
@wviana Thanks for this feature, I have only been using Paq a week, and I always look at the log after an update. Today I did an update, and went to open the log and there is an empty file, it says `[No Name]` at the bottom of the screen. This is a bug as the log is there at `/.cache/nvim/paq.log`.

Maybe the error is related to the out of order bug? Would be great to get it fixed :)

**Comment by wviana** [comment]
Hey @David-Else 
Just re-implemented this feature.
Do you have this bug as a issue or steps to reproduce it?

**Comment by David-Else** [comment]
@wviana Great you are doing a re-implementation! This bug never came back, it might have been me messing about with my config folders.

The bugs that are persistent are: https://github.com/savq/paq-nvim/issues/115 and https://github.com/savq/paq-nvim/issues/112 , I don't know if these apply to what you are doing.

**Pull request merged**
